set(Dough_Go_default_FILE_GROUP_assemble "")
set(Dough_Go_default_FILE_GROUP_assemblePreprocess "")
set(Dough_Go_default_FILE_GROUP_compile "c:/Users/Thomas/NAS_Files/Proofer_Project/Code Rev2/Dough_Go.X/main.c")
set(Dough_Go_default_FILE_GROUP_link "")
set(BUILD_LIBRARY 0)
set(Dough_Go_default_internal_image_name "c:/Users/Thomas/NAS_Files/Proofer_Project/Code Rev2/Dough_Go.X/_build/Dough_Go/default/default.elf")
set(Dough_Go_default_image_name "Dough_Go_default_default.elf")
set(Dough_Go_default_original_image_name "default.elf")
set(Dough_Go_default_output_dir "c:/Users/Thomas/NAS_Files/Proofer_Project/Code Rev2/Dough_Go.X/out/Dough_Go")
