M48
; DRILL file {KiCad 7.0.8} date Tue Dec  5 22:14:18 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-05T22:14:18-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X7.1902Y-2.2956
T2
X2.0079Y-0.748
X2.0079Y-3.6614
X7.2047Y-0.748
X7.2047Y-3.6614
T0
M30
